name: CI Workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: foundryai/spark-pytest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  verify-example:
    runs-on: ubuntu-latest
    env:
      working-directory: ./example
    steps:
      - uses: actions/checkout@master
      - name: Example pytest
        run: make spark-pytest
        working-directory: ${{env.working-directory}}

